In [0]:
from google.colab import drive
drive.mount('/content/gdrive')


Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
import os
os.chdir('gdrive/My Drive/text_mining/TP2')

In [0]:
!ls

Tweets.csv


In [0]:
os.chdir('

In [0]:
from google.colab import files
# Install Kaggle library

uploaded = files.upload()

Saving Tweets.csv to Tweets.csv


In [0]:

import numpy as np
import pandas as pd

# import dataset and take needed column

In [0]:
tweets_df = pd.read_csv ('Tweets.csv')


In [0]:
tweets_df.head()

tweet_id  ...               user_timezone
0  570306133677760513  ...  Eastern Time (US & Canada)
1  570301130888122368  ...  Pacific Time (US & Canada)
2  570301083672813571  ...  Central Time (US & Canada)
3  570301031407624196  ...  Pacific Time (US & Canada)
4  570300817074462722  ...  Pacific Time (US & Canada)

[5 rows x 15 columns]

In [0]:
tweets_df.isnull().sum()

tweet_id                            0
airline_sentiment                   0
airline_sentiment_confidence        0
negativereason                   5462
negativereason_confidence        4118
airline                             0
airline_sentiment_gold          14600
name                                0
negativereason_gold             14608
retweet_count                       0
text                                0
tweet_coord                     13621
tweet_created                       0
tweet_location                   4733
user_timezone                    4820
dtype: int64

In [0]:
tweets=tweets_df[['airline_sentiment','text']]

In [0]:
tweets.head()

airline_sentiment                                               text
0           neutral                @VirginAmerica What @dhepburn said.
1          positive  @VirginAmerica plus you've added commercials t...
2           neutral  @VirginAmerica I didn't today... Must mean I n...
3          negative  @VirginAmerica it's really aggressive to blast...
4          negative  @VirginAmerica and it's a really big bad thing...

In [0]:
import re
import nltk
nltk.download('stopwords')
#used once to download stopwords.
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!


# text preprocessing

In [0]:
#remove @ names

for i in range(0,len(tweets)):
    text=tweets['text'][i]

    list_words=text.split()

    list_words=[word for word in list_words if word[0]!='@']

    text = ' '.join(list_words)

    tweets['text'][i]=text

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2882: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)


In [0]:
#cleaning and preprocessing

for i in range(0,len(tweets['text'])):

  feed = re.sub('[^a-zA-Z]',' ',tweets['text'][i])
  feed = feed.lower()
  feed = feed.split()
  ps = PorterStemmer()
  #feed = [ps.stem(word) for word in feed if not word in set(stopwords.words('english'))]
  feed = ' '.join(feed)

  tweets['text'][i]=feed



/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2882: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  exec(code_obj, self.user_global_ns, self.user_ns)


In [0]:
tweets.head()

airline_sentiment                                               text
0           neutral                                          what said
1          positive  plus you ve added commercials to the experienc...
2           neutral  i didn t today must mean i need to take anothe...
3          negative  it s really aggressive to blast obnoxious ente...
4          negative           and it s a really big bad thing about it

# bag of words

In [0]:
from sklearn.model_selection import train_test_split


In [0]:
train_df,test_df = train_test_split(tweets, test_size=0.2, random_state=45)
train_df.shape,test_df.shape

((11712, 2), (2928, 2))

In [0]:
x_test = test_df['text']
y_test = test_df[['airline_sentiment']]

x_train = train_df['text']
y_train = train_df[['airline_sentiment']]

In [0]:
x_train.head()

5030     tfw ty spent total of hrs and mins holding cel...
11963    lost my cats missed their flights kept them cr...
5541     easy and pleasant difficult and stressful lear...
6506     done messed up now i have planned a trip to co...
9515                they told me to call back late flightr
Name: text, dtype: object

In [0]:
from sklearn.feature_extraction.text import CountVectorizer

In [0]:
#bag of words
parseur = CountVectorizer()
#create the document term matrix
XTrain = parseur.fit_transform(x_train)


#number of tokens
print(len(parseur.get_feature_names()))
#list of tokens
print(parseur.get_feature_names())

11368
['aa', 'aaaand', 'aaalwayslate', 'aadavantage', 'aadelay', 'aadv', 'aadvantage', 'aafail', 'aakjumxa', 'aal', 'aaron', 'aau', 'aavvoreph', 'aay', 'ab', 'aback', 'abandon', 'abandoned', 'abandonment', 'abassinet', 'abc', 'abcletjetbluestreamfeed', 'abcnews', 'abducted', 'abi', 'abilities', 'ability', 'able', 'aboard', 'aboout', 'abounds', 'about', 'above', 'abprg', 'abq', 'abroad', 'absolute', 'absolutely', 'absorb', 'absorber', 'absoulutely', 'absurd', 'absurdity', 'absurdly', 'abt', 'abundance', 'abuse', 'abused', 'abxrq', 'abysmal', 'ac', 'acarl', 'acc', 'accelerate', 'accept', 'acceptable', 'accepted', 'accepting', 'acces', 'access', 'accessibility', 'accessible', 'accessing', 'accident', 'accidentally', 'accomidating', 'accommodate', 'accommodating', 'accommodation', 'accommodations', 'accomplish', 'accomplished', 'according', 'accordingly', 'account', 'accountability', 'accounts', 'accrue', 'accruing', 'acct', 'accts', 'accumulation', 'accurate', 'accurately', 'accused', 'ac

In [0]:
#transform the sparse matrix into a numpy matrix
mdtTrain = XTrain.toarray()
#type of the matrix
print(type(mdtTrain))
#size of the matrix
print(mdtTrain.shape)
#frequency of the terms
freq_mots = np.sum(mdtTrain,axis=0)
print(freq_mots)
#arg sort
index = np.argsort(freq_mots)
print(index)
#print the terms and their frequency
imp = {'terme':np.asarray(parseur.get_feature_names())[index],'freq':freq_mots[index]}
print(pd.DataFrame(imp))

<class 'numpy.ndarray'>
(11712, 11368)
[248   1   1 ...   3   1   1]
[ 5683  6472  6471 ... 11242  9766  9930]
                  terme  freq
0                 loeco     1
1           nevertoldus     1
2           nevertakeno     1
3           neverontime     1
4      nevergettinghome     1
...                 ...   ...
11363            flight  3198
11364               for  3227
11365               you  3557
11366               the  4913
11367                to  6879

[11368 rows x 2 columns]


#### TFIDF

In [0]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer(norm="l2")
tfidf.fit(mdtTrain)
print ("IDF:",tfidf.idf_)
tf_idf_matrix = tfidf.transform(mdtTrain)
print (tf_idf_matrix.todense())

IDF: [4.9260369  9.67530743 9.67530743 ... 8.98216025 9.67530743 9.67530743]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [0]:
print(len(mdtTrain[1]))

11368


#models training and testing

##### Logistic Regression

In [0]:
#*** train the classifier
#import the class Logistic Regression
from sklearn.linear_model import LogisticRegression
#instatiate the object
modelFirst = LogisticRegression()
#perform the training process
modelFirst.fit(tf_idf_matrix,y_train)
#size of coefficients matrix
print(modelFirst.coef_.shape)


/usr/local/lib/python3.6/dist-packages/sklearn/utils/validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


(3, 11368)


In [0]:
#intercept
print(modelFirst.intercept_)
#generate the document term matrix for the test set
#using the object learned from the train set
#create the document term matrix
mdtTest = parseur.transform(x_test)
#size of the matrix
print(mdtTest.shape)
#prediction for the test set


[ 0.09008946  0.47480146 -0.56489092]
(2928, 11368)


In [0]:
print(mdtTest[0])

  (0, 165)	1
  (0, 279)	1
  (0, 372)	2
  (0, 701)	1
  (0, 730)	1
  (0, 875)	1
  (0, 1326)	1
  (0, 3050)	1
  (0, 3646)	1
  (0, 4019)	1
  (0, 4259)	1
  (0, 6627)	1
  (0, 6665)	1
  (0, 6772)	1
  (0, 6912)	1
  (0, 8735)	1
  (0, 9761)	1
  (0, 9766)	1
  (0, 9883)	1
  (0, 10454)	1


In [0]:
from sklearn.feature_extraction.text import TfidfTransformer
tfidf = TfidfTransformer(norm="l2")
tfidf.fit(mdtTest)
print ("IDF:",tfidf.idf_)
tf_idf_matrix_test = tfidf.transform(mdtTest)
print (tf_idf_matrix.todense())

IDF: [5.24474673 8.98241635 8.98241635 ... 8.28926917 8.98241635 8.98241635]
[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [0]:
print(tf_idf_matrix_test[0])

  (0, 10454)	0.177051590021993
  (0, 9883)	0.3484649638449292
  (0, 9766)	0.09509838636289047
  (0, 9761)	0.14137806397381378
  (0, 8735)	0.29990618579487016
  (0, 6912)	0.3484649638449292
  (0, 6772)	0.13435138802694832
  (0, 6665)	0.1619622820074981
  (0, 6627)	0.14595951855403647
  (0, 4259)	0.1458089217999065
  (0, 4019)	0.2183204530415558
  (0, 3646)	0.10733920003829263
  (0, 3050)	0.26461206211552313
  (0, 1326)	0.20278862969475214
  (0, 875)	0.17107334704699445
  (0, 730)	0.1925994598763529
  (0, 701)	0.2871906081072195
  (0, 372)	0.21684549281746604
  (0, 279)	0.17988388218870233
  (0, 165)	0.3484649638449292


In [0]:
predTest1 = modelFirst.predict(tf_idf_matrix_test)

In [0]:
#import the metrics class for the performance measurement
from sklearn import metrics
#confusion matrix
mcTest = metrics.confusion_matrix(y_test,predTest1)
print(mcTest)
#recall
print(metrics.recall_score(y_test,predTest1,pos_label='spam',average='weighted'))
#precision
print(metrics.precision_score(y_test,predTest1,pos_label='spam',average='weighted'))
#accuracy rate
print(metrics.accuracy_score(y_test,predTest1))
#F1-Score
print(metrics.f1_score(y_test,predTest1,pos_label='spam',average='weighted'))

[[1731   82   19]
 [ 261  321   41]
 [ 119   59  295]]
0.8015710382513661
0.795130675440171
0.8015710382513661
0.7903656739840894


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1321: UserWarning: Note that pos_label (set to 'spam') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)


##### random forest


In [0]:
from sklearn.ensemble import RandomForestClassifier

clf = RandomForestClassifier()


In [0]:
from sklearn import preprocessing


In [0]:
clf.fit(mdtTrain,y_train)

/usr/local/lib/python3.6/dist-packages/ipykernel_launcher.py:1: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  """Entry point for launching an IPython kernel.


RandomForestClassifier(bootstrap=True, ccp_alpha=0.0, class_weight=None,
                       criterion='gini', max_depth=None, max_features='auto',
                       max_leaf_nodes=None, max_samples=None,
                       min_impurity_decrease=0.0, min_impurity_split=None,
                       min_samples_leaf=1, min_samples_split=2,
                       min_weight_fraction_leaf=0.0, n_estimators=100,
                       n_jobs=None, oob_score=False, random_state=None,
                       verbose=0, warm_start=False)

In [0]:
predTest = clf.predict(mdtTest)

In [0]:
#import the metrics class for the performance measurement
from sklearn import metrics
#confusion matrix
mcTest = metrics.confusion_matrix(y_test,predTest)
print(mcTest)




#recall
print(metrics.recall_score(y_test,predTest,pos_label='spam',average='weighted'))
#precision
print(metrics.precision_score(y_test,predTest,pos_label='spam',average='weighted'))
#accuracy rate
print(metrics.accuracy_score(y_test,predTest))
#F1-Score
print(metrics.f1_score(y_test,predTest,pos_label='spam',average='weighted'))


[[1635  143   54]
 [ 242  333   48]
 [ 120   75  278]]
0.7670765027322405
0.7590369940292705
0.7670765027322405
0.7603402495057218


/usr/local/lib/python3.6/dist-packages/sklearn/metrics/_classification.py:1321: UserWarning: Note that pos_label (set to 'spam') is ignored when average != 'binary' (got 'weighted'). You may use labels=[pos_label] to specify a single positive class.
  % (pos_label, average), UserWarning)
